name: TypeDoc

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npx typedoc src/index.ts
      - uses: actions/upload-pages-artifact@v3
        with:
          path: doc/
      - uses: actions/deploy-pages@v4
